# Generated by Django 2.0.7 on 2018-10-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20181021_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments_text',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='email_user',
            field=models.EmailField(blank=True, max_length=70, verbose_name='Email пользователя'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='login_user',
            field=models.CharField(blank=True, max_length=40, verbose_name='Логин пользователя'),
        ),
    ]
